# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Service with Maven
on:
  push:
    branches: [ dependabot* ]
  pull_request:
    branches: [ master ]
jobs:
  dependency_scan:
    runs-on: ubuntu-latest
    name: Find secrets
    steps:
    # Checkout the source code so we have some files to look at.
    - uses: actions/checkout@v2
    # Run the secrets finder
    - name: secrets finder
      run: echo "placeholder for dependency scan"
